version: '3.1'

services:
  db:
    container_name: e-wallet-db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet
      TZ: 'GMT+5'
      PGTZ: 'GMT+5'
    volumes:
      - ./runtime/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432